name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install JupyterLab
      run: python -m pip install jupyterlab nbresuse

    - name: Build and install the extension
      run: |
        jlpm
        jlpm run build
        jlpm run link

    - name: Browser check
      run: python -m jupyterlab.browser_check

    - name: Lint
      run: jlpm run lint:check