name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '12.x'

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install JupyterLab
      run: |
        python -m pip install jupyterlab --pre
        python -m pip install nbresuse

    - name: Install the extension
      run: |
        python -m pip install -e .
        jupyter labextension list 2>&1 | grep -ie "jupyterlab-system-monitor.*OK"

    - name: Browser check
      run: python -m jupyterlab.browser_check

    - name: Lint
      run: jlpm run lint:check